### ISSUE TITLE
eas build fails with error: Package "react-native-vad" does not contain a valid config plugin.

### ISSUE THREAD

**Issue by worldreboot** [frymanofer/ReactNative_VAD#1]
When running:
`eas build --profile development --platform android`

I get the following error:
```
Package "react-native-vad" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
    Error: build command failed.
```

app.json:
```
"plugins": [
      "react-native-vad",
    ],
```

**Comment by MukamaMuhammad** [comment]
Have you been able to solve this? I get the same error as well

**Comment by frymanofer** [comment]
Hi - sorry, the plugin.js was not added to the package by accident. I added it now and checked it is in.
Since I do not have an EAS account I cannot test it right now. Can you please upgrade your react-native-vad version and test?

**Comment by MukamaMuhammad** [comment]
I have upgraded to version 1.0.33 but still get the same error
`PluginError: Package "react-native-vad" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\react-native-vad\vad\index.js:2
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at requirePluginFile (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:207:12)
    at resolveConfigPluginFunctionWithInfo (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:148:14)`

**Comment by frymanofer** [comment]
Hi - can you please try with the latest version? 1.0.34? 
I fixed a few things and managed to run:
npx expo prebuild and eas build
Thanks,
Ofer

**Comment by MukamaMuhammad** [comment]
The prebuild runs successfully now but I still get this error

```
 > Configure project :react-native-reanimated

Android gradle plugin: 8.6.0
Gradle: 8.10.2

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.davoice:vad:1.0.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/davoice/vad/1.0.0/vad-1.0.0.pom
       - https://repo.maven.apache.org/maven2/com/davoice/vad/1.0.0/vad-1.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/davoice/vad/1.0.0/vad-1.0.0.pom
       - https://www.jitpack.io/com/davoice/vad/1.0.0/vad-1.0.0.pom
       - file:/D:/PROJECTS/THERAPY%20AI/therapy-ai/node_modules/react-native/android/com/davoice/vad/1.0.0/vad-1.0.0.pom
       - file:/D:/PROJECTS/THERAPY%20AI/therapy-ai/node_modules/jsc-android/dist/com/davoice/vad/1.0.0/vad-1.0.0.pom       
     Required by:
         project :app > project :react-native-vad

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 33s
23 actionable tasks: 5 executed, 18 up-to-date
Error: D:\PROJECTS\THERAPY AI\therapy-ai\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: D:\PROJECTS\THERAPY AI\therapy-ai\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\spawn-async\src\spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.cp.emit (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\spawn-async\src\spawnAsync.ts:28:21)
    at spawnGradleAsync (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:134:28)
    at assembleAsync (D:\PROJECTS\THERAPY AI\therapy-ai\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:83:16)
    at runAndroidAsync (D:\PROJECTS\THERAPY 

>  #AI\therapy-ai\node_modules\@expo\cli\src\run\android\runAndroidAsync.ts:48:24) 
````

**Comment by chisanen** [comment]
Hello @frymanofer any guidance here?

**Comment by mononices** [comment]
@MukamaMuhammad hello, have you been able to fix this issue? I have it too, unfortunately with Expo

**Comment by mononices** [comment]
@frymanofer hi, can you provide any insights on dealing with gradle not finding com.davoice:vad:1.0.0?

**Comment by ajeecai** [comment]
> [@frymanofer](https://github.com/frymanofer) hi, can you provide any insights on dealing with gradle not finding com.davoice:vad:1.0.0?

Same issue.
